### ISSUE TITLE
actsim is unable to inspect member variables of types

### ISSUE THREAD

**Issue by nbingham1** [rmanohar/actsim#12]
bug4.act
```
deftype thing(bool y) {}

defproc test() {
  thing x;
}
```
actsim.conf
```
begin level
 string default "prs"
end
```
**Expected Behavior**
actsim successfully sets x.y to 0 and the simulation continues.

**Observed Behavior**
actsim doesn't recognize x.y as a variable.
```
$ actsim -Tsky130 bug4.act test
actsim> set x.y 0
Could not find identifier `x.y' within process `test<>'
Execution aborted.
Stack trace:
	called from: set
	called from: -top-level-
```
**System Information**
```
LSB Version:	core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Xyce DEVELOPMENT-202211202002-(Public_Release-7.6.0-16-g7ac86b45)-opensource

actsim commit e93e9cb71300329a68095a140112e6a07a879d3f
```

**Comment by rmanohar** [comment]
When a variable is entirely unused, actsim removes it from the simulation. Also, note that it's not enough for the variable to be used in say a log statement; it has to be part of the circuit. There are no chp-level optimizations performed in actsim itself, so you don't have to worry about optimizations eliminating variables.

**Comment by nbingham1** [comment]
Gotcha, I added a production rule on x.y and then was able to inspect. We may want to detect when the user is trying to access a variable that's been optimized out and no-op it.
